name: Action workflow
on:
  repository_dispatch:
    types: [build] 
  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"

  pull_request:
    types: ["closed", "assigned", "opnened", "reopened"]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
     # Step 1

      - name: Client Payload
        run: echo ${{ github.event.client_payload.env }}

      - name: List BEFORE Checkout & echo Main vars
        run: | 
          pwd
          ls -al
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          echo "Done."

      - name: Checkout Code Task
        uses: actions/checkout@v2

      - name: List Files AFTER Checkout
        run: | 
          pwd
          ls -al

      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Vivian'
      # Step 2
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"