# workflow name
name: Tokens
# trigger
on: ['push']
# jobs
jobs:
  # job name 1..n
  test-token-job:
    # runner env
    runs-on: ubuntu-latest
    # jobs steps
    steps:
     # Command Step
      - name: Print Token
        run: echo "${{ secrets.GITHUB_TOKEN }}"

      - name: Submit and Issue
        run: |
           curl --request POST \
              --url https://api.github.com/repos/${{ github.repository }}/issues \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'content-type: application/json' \
              --data '{
                  "title": "Automated issue for commit: ${{ github.sha }}",
                  "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
                }'